name: hands_train_job_g1.1
desc: Script which uses DataSphere project resources – project disk, datasets.
cmd: /workspace/run.sh ${HANDS_DS} ${MODEL}
env:
  docker:
    image: xhoopoe/pytorch:biohack
outputs:
  - hands.pkl: MODEL
datasets:
  - bt15u3bsavamvi6j1r21: HANDS_DS
flags:
  - attach-project-disk
cloud-instance-type: g1.1